# Generated by Django 3.0.4 on 2020-03-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('world', models.CharField(max_length=200)),
                ('length', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('difficulty', models.FloatField()),
                ('badgeXP', models.IntegerField()),
                ('event', models.BooleanField()),
            ],
        ),
    ]
