# Generated by Django 3.0.4 on 2020-03-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='min_level',
            field=models.IntegerField(default=0),
        ),
    ]
