# Generated by Django 3.0.4 on 2020-03-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_route_min_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='badgeXP',
            field=models.IntegerField(verbose_name='Badge XP'),
        ),
        migrations.AlterField(
            model_name='route',
            name='elevation',
            field=models.IntegerField(verbose_name='Elevation (m)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.FloatField(verbose_name='Length (km)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Route Name'),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_time', models.FloatField(verbose_name='Total Time')),
                ('active_time', models.FloatField(verbose_name='Active Time')),
                ('date', models.DateField()),
                ('max_power', models.IntegerField(verbose_name='Max Power')),
                ('avg_power', models.IntegerField(verbose_name='Average Power')),
                ('max_hr', models.IntegerField(verbose_name='Max Heartrate')),
                ('avg_hr', models.IntegerField(verbose_name='Average Heartrate')),
                ('act_dist', models.FloatField(verbose_name='Actual Distance (m)')),
                ('calories', models.IntegerField()),
                ('total_work', models.IntegerField(verbose_name='Total Work (kJ)')),
                ('avg_cadence', models.IntegerField(verbose_name='Average Cadence')),
                ('max_cadence', models.IntegerField(verbose_name='Max Cadence')),
                ('act_elevation', models.IntegerField(verbose_name='Actual Elevation Gain (m)')),
                ('avg_spd', models.FloatField(verbose_name='Average Speed (kph)')),
                ('max_spd', models.FloatField(verbose_name='Maximum Speed (kph)')),
                ('route', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='rides.Route')),
            ],
        ),
    ]
